export enum TaskStatus {
  UNASSIGNED = 'UNASSIGNED',
  BACKLOG = 'BACKLOG',
  TODO = 'TODO',
  PLANNED = 'PLANNED',
  WAITING = 'WAITING',
  READY = 'READY',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  BLOCKED = 'BLOCKED',
  DONE = 'DONE',
  N_A = 'N_A',
  CANCELED = 'CANCELED',
}

export enum TaskPriority {
  URGENT = 'URGENT',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  NONE = 'NONE',
}

export enum DependencyType {
  FINISH_TO_START = 'FINISH_TO_START',
}

export enum ReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TaskActionType {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  PROGRESS_UPDATED = 'PROGRESS_UPDATED',
  ASSIGNED = 'ASSIGNED',
  UNASSIGNED = 'UNASSIGNED',
  DEPENDENCY_ADDED = 'DEPENDENCY_ADDED',
  DEPENDENCY_REMOVED = 'DEPENDENCY_REMOVED',
  AUTOMATICALLY_UNBLOCKED = 'AUTOMATICALLY_UNBLOCKED',
  AUTOMATICALLY_BLOCKED = 'AUTOMATICALLY_BLOCKED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  ATTACHMENT_ADDED = 'ATTACHMENT_ADDED',
  REVIEW_REQUESTED = 'REVIEW_REQUESTED',
  REVIEW_APPROVED = 'REVIEW_APPROVED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
}
