import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        fx: {
          // FutureX Refined Neutral Background System
          bg: {
            app: '#F8F9FA',
            subtle: '#F1F5F9',
            muted: '#E2E8F0',
            canvas: '#F8F9FA',
            surface: '#FFFFFF',
            secondary: '#F8FAFC',
            soft: '#F1F5F9',
            tertiary: '#E2E8F0',
            hover: '#F8FAFC',
            DEFAULT: '#FFFFFF',
          },
          surface: {
            DEFAULT: '#FFFFFF',
            secondary: '#F8FAFC',
            soft: '#F1F5F9',
            tertiary: '#E2E8F0',
          },
          // Restrained Neutral Typography
          text: {
            primary: '#0F172A',
            secondary: '#475569',
            tertiary: '#64748B',
            muted: '#94A3B8',
            disabled: '#CBD5E1',
          },
          // Calm Borders
          border: {
            subtle: '#E2E8F0',
            medium: '#CBD5E1',
            DEFAULT: '#E2E8F0',
            strong: '#94A3B8',
          },
          // Restrained Primary Blue System
          blue: {
            50: '#F8FAFC',
            100: '#EFF6FF',
            500: '#2563EB',
            600: '#2563EB',
            700: '#1D4ED8',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EFF6FF',
            verySoft: '#F8FAFC',
            DEFAULT: '#2563EB',
          },
          primary: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EFF6FF',
            verySoft: '#F8FAFC',
            ring: 'rgba(37, 99, 235, 0.15)',
          },
          accent: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EFF6FF',
            verySoft: '#F8FAFC',
            subtle: '#F1F5F9',
          },
          // Strict Semantic Status System (Soft & Clean)
          semantic: {
            completed: '#15803D',
            completedBg: '#F0FDF4',
            ready: '#475569',
            readyBg: '#F1F5F9',
            inProgress: '#1D4ED8',
            inProgressBg: '#EFF6FF',
            waiting: '#B45309',
            waitingBg: '#FFFBEB',
            inReview: '#6D28D9',
            inReviewBg: '#F5F3FF',
            blocked: '#DC2626',
            blockedBg: '#FEF2F2',
            unassigned: '#64748B',
            unassignedBg: '#F8FAFC',
            // Aliases
            done: '#15803D',
            doneBg: '#F0FDF4',
            highPriority: '#C2410C',
            highPriorityBg: '#FFF7ED',
            danger: '#DC2626',
            dangerBg: '#FEF2F2',
            warning: '#B45309',
            warningBg: '#FFFBEB',
            info: '#1D4ED8',
            infoBg: '#EFF6FF',
            success: '#15803D',
            successBg: '#F0FDF4',
          },
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        badge: '6px',
        btn: '8px',
        input: '8px',
        row: '10px',
        surface: '12px',
        DEFAULT: '10px',
        md: '10px',
        panel: '14px',
        card: '14px',
        utility: '14px',
        dialog: '16px',
        modal: '16px',
        popover: '12px',
        '2xl': '14px',
        '3xl': '16px',
      },
      boxShadow: {
        none: 'none',
        subtle: '0 1px 2px rgba(15, 23, 42, 0.03)',
        xs: '0 1px 2px rgba(15, 23, 42, 0.03)',
        sm: '0 1px 3px rgba(15, 23, 42, 0.04), 0 1px 2px -1px rgba(15, 23, 42, 0.02)',
        card: '0 1px 3px rgba(15, 23, 42, 0.03), 0 1px 2px -1px rgba(15, 23, 42, 0.02)',
        popover: '0 8px 24px rgba(15, 23, 42, 0.06), 0 1px 3px rgba(0, 0, 0, 0.03)',
        modal: '0 12px 32px rgba(15, 23, 42, 0.08), 0 2px 6px rgba(0, 0, 0, 0.03)',
        drawer: '-4px 0 24px 0 rgba(0, 0, 0, 0.05)',
      },
      keyframes: {
        fxFadeIn: {
          from: { opacity: '0', transform: 'translateY(1px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fxDrawerIn: {
          from: { opacity: '0', transform: 'translateX(8px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        fxDialogIn: {
          from: { opacity: '0', transform: 'scale(0.99)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        fxDropdownIn: {
          from: { opacity: '0', transform: 'translateY(2px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeIn: 'fxFadeIn 130ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        drawerIn: 'fxDrawerIn 190ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        dialogIn: 'fxDialogIn 170ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        dropdownIn: 'fxDropdownIn 130ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      zIndex: {
        base: '0',
        sticky: '10',
        header: '30',
        dropdown: '50',
        popover: '50',
        drawer: '60',
        backdrop: '70',
        modal: '80',
        toast: '90',
      },
    },
  },
  plugins: [],
};

export default config;
