import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        fx: {
          // FutureX Refined Neutral Surface System
          bg: {
            app: '#FFFFFF',
            canvas: '#F7F8FA',
            secondary: '#F7F8FA',
            soft: '#F2F4F7',
            surface: '#FFFFFF',
            subtle: '#F7F8FA',
            muted: '#E3E7EC',
            hover: '#F2F4F7',
            tertiary: '#E3E7EC',
            DEFAULT: '#FFFFFF',
          },
          surface: {
            DEFAULT: '#FFFFFF',
            secondary: '#F7F8FA',
            soft: '#F2F4F7',
            tertiary: '#E3E7EC',
          },
          // Restrained Neutral Typography
          text: {
            primary: '#181B20',
            secondary: '#626A73',
            tertiary: '#626A73',
            muted: '#929AA3',
            disabled: '#CBD5E1',
          },
          // Calm Borders
          border: {
            subtle: '#E3E7EC',
            medium: '#D4DAE1',
            DEFAULT: '#E3E7EC',
            strong: '#D4DAE1',
          },
          // Restrained Primary Blue System
          blue: {
            50: '#F6F9FF',
            100: '#EEF4FF',
            500: '#2563EB',
            600: '#2563EB',
            700: '#1D4ED8',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EEF4FF',
            verySoft: '#F6F9FF',
            DEFAULT: '#2563EB',
          },
          primary: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EEF4FF',
            verySoft: '#F6F9FF',
            ring: 'rgba(37, 99, 235, 0.15)',
          },
          accent: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EEF4FF',
            verySoft: '#F6F9FF',
            subtle: '#F2F4F7',
          },
          // Strict Semantic Status System (Soft, Clean, Independent from Blue)
          semantic: {
            completed: '#237A57',
            completedBg: '#EDF8F2',
            ready: '#237A57',
            readyBg: '#EDF8F2',
            inProgress: '#2563EB',
            inProgressBg: '#EEF4FF',
            waiting: '#A86B12',
            waitingBg: '#FFF6E5',
            inReview: '#7557B5',
            inReviewBg: '#F4F0FC',
            blocked: '#C24141',
            blockedBg: '#FDEEEE',
            unassigned: '#626A73',
            unassignedBg: '#F7F8FA',
            // Aliases
            done: '#237A57',
            doneBg: '#EDF8F2',
            highPriority: '#C24141',
            highPriorityBg: '#FDEEEE',
            danger: '#C24141',
            dangerBg: '#FDEEEE',
            warning: '#A86B12',
            warningBg: '#FFF6E5',
            info: '#2563EB',
            infoBg: '#EEF4FF',
            success: '#237A57',
            successBg: '#EDF8F2',
          },
        },
      },
      fontFamily: {
        sans: [
          'ui-sans-serif',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        badge: '6px',
        btn: '9px',
        input: '9px',
        row: '10px',
        surface: '12px',
        DEFAULT: '10px',
        md: '10px',
        panel: '14px',
        card: '14px',
        utility: '12px',
        dialog: '16px',
        modal: '16px',
        popover: '12px',
        '2xl': '14px',
        '3xl': '16px',
      },
      boxShadow: {
        none: 'none',
        subtle: 'none',
        xs: '0 1px 2px rgba(24, 27, 32, 0.02)',
        sm: '0 1px 3px rgba(24, 27, 32, 0.03)',
        card: 'none',
        popover: '0 4px 16px rgba(24, 27, 32, 0.06), 0 1px 3px rgba(0, 0, 0, 0.03)',
        modal: '0 8px 24px rgba(24, 27, 32, 0.08), 0 2px 6px rgba(0, 0, 0, 0.03)',
        drawer: '-2px 0 16px rgba(0, 0, 0, 0.05)',
      },
      keyframes: {
        fxFadeIn: {
          from: { opacity: '0', transform: 'translateY(1px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fxDrawerIn: {
          from: { opacity: '0', transform: 'translateX(6px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        fxDialogIn: {
          from: { opacity: '0', transform: 'scale(0.99)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        fxDropdownIn: {
          from: { opacity: '0', transform: 'translateY(2px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeIn: 'fxFadeIn 130ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        drawerIn: 'fxDrawerIn 170ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        dialogIn: 'fxDialogIn 160ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
        dropdownIn: 'fxDropdownIn 130ms cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      zIndex: {
        base: '0',
        sticky: '10',
        header: '30',
        dropdown: '50',
        popover: '50',
        drawer: '60',
        backdrop: '70',
        modal: '80',
        toast: '90',
      },
    },
  },
  plugins: [],
};

export default config;
