import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        fx: {
          // FutureX Primary Blue Accent System
          primary: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            soft: '#EEF4FF',
            verySoft: '#F6F9FF',
            navy: '#163A5F',
            ring: 'rgba(37, 99, 235, 0.20)',
          },
          accent: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            dark: '#1E40AF',
            soft: '#EEF4FF',
            verySoft: '#F6F9FF',
            ring: 'rgba(37, 99, 235, 0.20)',
            subtle: '#F7F8FA',
            secondary: '#1D4ED8',
          },
          blue: {
            DEFAULT: '#2563EB',
            hover: '#1D4ED8',
            pressed: '#1E40AF',
            dark: '#163A5F',
            soft: '#EEF4FF',
            verySoft: '#F6F9FF',
            50: '#F6F9FF',
            100: '#EEF4FF',
            500: '#2563EB',
            600: '#1D4ED8',
            700: '#1E40AF',
            800: '#163A5F',
          },
          bg: {
            app: '#FFFFFF',
            canvas: '#FFFFFF',
            surface: '#FFFFFF',
            secondary: '#F7F8FA',
            soft: '#F2F4F7',
            tertiary: '#F2F4F7',
            subtle: '#F7F8FA',
            hover: '#F7F8FA',
            DEFAULT: '#FFFFFF',
          },
          surface: {
            DEFAULT: '#FFFFFF',
            secondary: '#F7F8FA',
            soft: '#F2F4F7',
            tertiary: '#F2F4F7',
          },
          text: {
            primary: '#181B20',
            secondary: '#626A73',
            muted: '#929AA3',
            disabled: '#B8B2AC',
          },
          border: {
            DEFAULT: '#E3E7EC',
            strong: '#D4DAE1',
            subtle: '#E3E7EC',
          },
          // Strict Semantic Status Colors
          semantic: {
            ready: '#237A57',
            readyBg: '#EDF8F2',
            readyBorder: '#C6E7D2',
            inProgress: '#2563EB',
            inProgressBg: '#EEF4FF',
            inProgressBorder: '#BDE0FF',
            waiting: '#A86B12',
            waitingBg: '#FFF6E5',
            waitingBorder: '#FDE9B8',
            inReview: '#7557B5',
            inReviewBg: '#F4F0FC',
            inReviewBorder: '#E6D8FF',
            blocked: '#C24141',
            blockedBg: '#FDEEEE',
            blockedBorder: '#F9D1D1',
            done: '#237A57',
            doneBg: '#EDF8F2',
            doneBorder: '#C6E7D2',
            highPriority: '#B45A20',
            highPriorityBg: '#FFF1E7',
            danger: '#C24141',
            dangerBg: '#FDEEEE',
            warning: '#A86B12',
            warningBg: '#FFF6E5',
            info: '#2563EB',
            infoBg: '#EEF4FF',
            success: '#237A57',
            successBg: '#EDF8F2',
          },
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Inter',
          'system-ui',
          'sans-serif',
        ],
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        badge: '6px',
        btn: '10px',
        input: '10px',
        DEFAULT: '10px',
        md: '10px',
        row: '12px',
        card: '14px',
        utility: '14px',
        panel: '16px',
        popover: '14px',
        modal: '18px',
        dialog: '18px',
        '2xl': '16px',
        '3xl': '18px',
      },
      boxShadow: {
        none: 'none',
        subtle: '0 1px 2px rgba(15, 23, 42, 0.03)',
        card: '0 1px 2px rgba(15, 23, 42, 0.03)',
        xs: '0 1px 2px rgba(15, 23, 42, 0.03)',
        sm: '0 1px 2px rgba(15, 23, 42, 0.03)',
        popover: '0 10px 30px rgba(15, 23, 42, 0.08), 0 1px 3px rgba(0, 0, 0, 0.04)',
        modal: '0 10px 30px rgba(15, 23, 42, 0.08), 0 2px 6px rgba(0, 0, 0, 0.04)',
        drawer: '-4px 0 24px 0 rgba(0, 0, 0, 0.06)',
      },
      keyframes: {
        fxFadeIn: {
          from: { opacity: '0', transform: 'translateY(1px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        fadeIn: 'fxFadeIn 120ms ease-out forwards',
      },
      zIndex: {
        base: '0',
        sticky: '10',
        header: '30',
        dropdown: '50',
        popover: '50',
        drawer: '60',
        backdrop: '70',
        modal: '80',
        toast: '90',
      },
    },
  },
  plugins: [],
};

export default config;
