import { PrismaClient } from "@prisma/client";

const TEMPLATE_VERSION = "2026.09";
const ALL_PRODUCT_TYPES = ["APP", "GAME", "WEBSITE_TOOL"];

type ChecklistSeedItem = {
  code: string;
  phase: string;
  stage: string;
  title: string;
  doneWhen: string;
  mandatory?: boolean;
  ownerRole: string;
  defaultOrder: number;
  requiresReview?: boolean;
  allowParallelWork?: boolean;
  dependencies?: string[];
  applicableTypes?: string[];
};

const checklistItems: ChecklistSeedItem[] = [
  {
    code: "PD-01",
    phase: "1. Concept",
    stage: "At idea approval",
    title: "Write one-paragraph product concept and primary user problem",
    doneWhen: "Concept brief approved",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 1,
    dependencies: [],
  },
  {
    code: "PD-02",
    phase: "1. Concept",
    stage: "At idea approval",
    title: "Define target users, country/language and core value proposition",
    doneWhen: "Target audience documented",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 2,
    dependencies: ["PD-01"],
  },
  {
    code: "PD-03",
    phase: "1. Concept",
    stage: "Before planning",
    title: "Define business model / monetisation approach",
    doneWhen: "Monetisation route approved",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 3,
    dependencies: ["PD-02"],
  },
  {
    code: "PD-04",
    phase: "1. Concept",
    stage: "Before planning",
    title: "Review comparable products and define differentiation",
    doneWhen: "Competition notes + differentiation",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 4,
    dependencies: ["PD-02"],
  },
  {
    code: "PD-05",
    phase: "2. Scope",
    stage: "After concept approval",
    title: "Define MVP / Version 1 features",
    doneWhen: "Approved V1 feature list",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 5,
    dependencies: ["PD-03", "PD-04"],
  },
  {
    code: "PD-06",
    phase: "2. Scope",
    stage: "After concept approval",
    title: "Separate Must Have / Should Have / Later features",
    doneWhen: "Prioritized scope",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 6,
    dependencies: ["PD-05"],
  },
  {
    code: "PD-07",
    phase: "2. Scope",
    stage: "Before development",
    title: "Define screens, game modes or major user flows",
    doneWhen: "Flow/screen list approved",
    ownerRole: "PM_DESIGNER",
    defaultOrder: 7,
    dependencies: ["PD-06"],
  },
  {
    code: "PD-08",
    phase: "2. Scope",
    stage: "Before development",
    title:
      "Identify external dependencies: APIs, SDKs, DCB, ads, backend, permissions",
    doneWhen: "Dependency list documented",
    ownerRole: "LEAD_DEVELOPER",
    defaultOrder: 8,
    dependencies: ["PD-06"],
  },
  {
    code: "PD-09",
    phase: "2. Scope",
    stage: "Before development",
    title: "Estimate development effort and assign team",
    doneWhen: "Owners and estimate confirmed",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 9,
    dependencies: ["PD-08"],
  },
  {
    code: "PD-10",
    phase: "2. Scope",
    stage: "Before development",
    title: "Set kickoff, internal build, QA, submission and launch dates",
    doneWhen: "Milestones recorded",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 10,
    dependencies: ["PD-09"],
  },
  {
    code: "PD-11",
    phase: "3. Design",
    stage: "Before implementation",
    title: "Prepare user flow / gameplay flow",
    doneWhen: "Flow approved",
    ownerRole: "PM_DESIGNER",
    defaultOrder: 11,
    dependencies: ["PD-07"],
  },
  {
    code: "PD-12",
    phase: "3. Design",
    stage: "Before implementation",
    title: "Create UI wireframes / HUD / menu structure",
    doneWhen: "Wireframes approved",
    ownerRole: "DESIGNER",
    defaultOrder: 12,
    dependencies: ["PD-11"],
  },
  {
    code: "PD-13",
    phase: "3. Design",
    stage: "Before implementation",
    title: "Create final UI visual design / design system",
    doneWhen: "Final UI assets ready",
    ownerRole: "DESIGNER",
    defaultOrder: 13,
    dependencies: ["PD-12"],
  },
  {
    code: "PD-14",
    phase: "3. Design",
    stage: "Before implementation",
    title: "Prepare required 2D/3D assets, animations, audio and content list",
    doneWhen: "Asset checklist approved",
    ownerRole: "DESIGNER_ARTIST",
    defaultOrder: 14,
    dependencies: ["PD-13"],
  },
  {
    code: "PD-15",
    phase: "4. Technical Setup",
    stage: "At development start",
    title: "Create repository/project and standard folder/branch structure",
    doneWhen: "Project initialized",
    ownerRole: "LEAD_DEVELOPER",
    defaultOrder: 15,
    dependencies: ["PD-10"],
  },
  {
    code: "PD-16",
    phase: "4. Technical Setup",
    stage: "At development start",
    title: "Configure package/application ID, environments and build settings",
    doneWhen: "Build config recorded",
    ownerRole: "DEVELOPER",
    defaultOrder: 16,
    dependencies: ["PD-15"],
  },
  {
    code: "PD-17",
    phase: "4. Technical Setup",
    stage: "Early development",
    title: "Set up backend/database/authentication if required",
    doneWhen: "Backend foundation works",
    mandatory: false,
    ownerRole: "DEVELOPER",
    defaultOrder: 17,
    dependencies: ["PD-15"],
  },
  {
    code: "PD-18",
    phase: "4. Technical Setup",
    stage: "Early development",
    title: "Integrate analytics/crash reporting foundation",
    doneWhen: "Events/crashes can be observed",
    ownerRole: "DEVELOPER",
    defaultOrder: 18,
    dependencies: ["PD-17"],
  },
  {
    code: "PD-19",
    phase: "5. Core Development",
    stage: "Development sprint",
    title: "Implement primary user loop / core gameplay",
    doneWhen: "Core loop works end-to-end",
    ownerRole: "DEVELOPER",
    defaultOrder: 19,
    dependencies: ["PD-13", "PD-16"],
  },
  {
    code: "PD-20",
    phase: "5. Core Development",
    stage: "Development sprint",
    title: "Implement screens, navigation and major features",
    doneWhen: "V1 features functional",
    ownerRole: "DEVELOPER",
    defaultOrder: 20,
    dependencies: ["PD-19"],
  },
  {
    code: "PD-21",
    phase: "5. Core Development",
    stage: "Development sprint",
    title: "Integrate backend/API/content systems",
    doneWhen: "Required systems functioning",
    mandatory: false,
    ownerRole: "DEVELOPER",
    defaultOrder: 21,
    dependencies: ["PD-17", "PD-20"],
  },
  {
    code: "PD-22",
    phase: "5. Core Development",
    stage: "Development sprint",
    title: "Implement save/progress/settings/localisation",
    doneWhen: "Save/local settings working",
    ownerRole: "DEVELOPER",
    defaultOrder: 22,
    dependencies: ["PD-20"],
  },
  {
    code: "PD-23",
    phase: "5. Core Development",
    stage: "Before QA",
    title: "Integrate monetization: ads / IAP / DCB as applicable",
    doneWhen: "Monetization test passes",
    ownerRole: "DEVELOPER",
    defaultOrder: 23,
    dependencies: ["PD-20"],
    applicableTypes: ["APP", "GAME"],
  },
  {
    code: "PD-24",
    phase: "5. Core Development",
    stage: "Before QA",
    title: "Implement required analytics events and conversion tracking",
    doneWhen: "Event checklist passes",
    ownerRole: "DEVELOPER",
    defaultOrder: 24,
    dependencies: ["PD-18", "PD-20"],
  },
  {
    code: "PD-25",
    phase: "5. Core Development",
    stage: "Before QA",
    title: "Implement privacy, consent and permission flows",
    doneWhen: "Compliance flows work",
    ownerRole: "DEVELOPER",
    defaultOrder: 25,
    dependencies: ["PD-17", "PD-20"],
  },
  {
    code: "PD-26",
    phase: "6. Internal Build",
    stage: "Before formal QA",
    title: "Create feature-complete internal build",
    doneWhen: "Build shared with PM/QA",
    ownerRole: "DEVELOPER",
    defaultOrder: 26,
    dependencies: ["PD-21", "PD-22", "PD-23", "PD-24", "PD-25"],
  },
  {
    code: "PD-27",
    phase: "6. Internal Build",
    stage: "Before formal QA",
    title: "Run developer self-test on main flows and devices",
    doneWhen: "Critical self-test passed",
    ownerRole: "DEVELOPER",
    defaultOrder: 27,
    dependencies: ["PD-26"],
  },
  {
    code: "PD-28",
    phase: "6. Internal Build",
    stage: "Before formal QA",
    title: "Check performance: loading, memory, crashes and network behavior",
    doneWhen: "Performance acceptable",
    ownerRole: "DEVELOPER",
    defaultOrder: 28,
    dependencies: ["PD-27"],
  },
  {
    code: "PD-29",
    phase: "7. QA",
    stage: "QA phase",
    title:
      "Test installation, first launch, onboarding, registration/subscription and onboarding",
    doneWhen: "Critical entry flows pass",
    ownerRole: "QA_PM",
    defaultOrder: 29,
    dependencies: ["PD-26"],
  },
  {
    code: "PD-30",
    phase: "7. QA",
    stage: "QA phase",
    title: "Test all V1 features / missions / screens against scope",
    doneWhen: "Feature QA complete",
    ownerRole: "QA_PM",
    defaultOrder: 30,
    dependencies: ["PD-29"],
  },
  {
    code: "PD-31",
    phase: "7. QA",
    stage: "QA phase",
    title: "Test monetisation, analytics and purchase/subscription callbacks",
    doneWhen: "Revenue/tracking flows pass",
    ownerRole: "QA_PM",
    defaultOrder: 31,
    dependencies: ["PD-23", "PD-24"],
    applicableTypes: ["APP", "GAME"],
  },
  {
    code: "PD-32",
    phase: "7. QA",
    stage: "QA phase",
    title: "Test low-end device, network loss, interruptions and edge cases",
    doneWhen: "Risk scenarios tested",
    ownerRole: "QA_PM",
    defaultOrder: 32,
    dependencies: ["PD-30"],
  },
  {
    code: "PD-33",
    phase: "7. QA",
    stage: "QA phase",
    title: "Log bugs, assign severity/owner and retest fixes",
    doneWhen: "No open launch-blocker bugs",
    ownerRole: "QA_PM",
    defaultOrder: 33,
    dependencies: ["PD-30", "PD-31", "PD-32"],
  },
  {
    code: "PD-34",
    phase: "8. Store & Compliance",
    stage: "Before submission",
    title:
      "Prepare app/game name, description, category and content rating inputs",
    doneWhen: "Store metadata ready",
    ownerRole: "MARKETING_PM",
    defaultOrder: 34,
    dependencies: ["PD-05"],
  },
  {
    code: "PD-35",
    phase: "8. Store & Compliance",
    stage: "Before submission",
    title:
      "Prepare icon, screenshots, feature graphic/video and localized assets",
    doneWhen: "Store creatives ready",
    ownerRole: "MARKETING_DESIGNER",
    defaultOrder: 35,
    dependencies: ["PD-13", "PD-34"],
  },
  {
    code: "PD-36",
    phase: "8. Store & Compliance",
    stage: "Before submission",
    title:
      "Prepare privacy policy, terms/support URL and data-safety disclosures",
    doneWhen: "Compliance assets ready",
    ownerRole: "PM_DEVELOPER",
    defaultOrder: 36,
    dependencies: ["PD-25", "PD-34"],
  },
  {
    code: "PD-37",
    phase: "8. Store & Compliance",
    stage: "Before submission",
    title:
      "Create product on required store/telco portals and complete metadata",
    doneWhen: "Portal entry created",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 37,
    dependencies: ["PD-34", "PD-35", "PD-36"],
  },
  {
    code: "PD-38",
    phase: "8. Store & Compliance",
    stage: "Before launch",
    title: "Complete required production/testing approvals",
    doneWhen: "Approval path complete",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 38,
    dependencies: ["PD-37"],
  },
  {
    code: "PD-39",
    phase: "9. Release",
    stage: "Release candidate",
    title: "Generate signed release candidate / production build",
    doneWhen: "RC build archived",
    ownerRole: "DEVELOPER",
    defaultOrder: 39,
    dependencies: ["PD-33", "PD-38"],
  },
  {
    code: "PD-40",
    phase: "9. Release",
    stage: "Release candidate",
    title: "Final smoke test using production configuration",
    doneWhen: "Smoke test passed",
    ownerRole: "QA_PM",
    defaultOrder: 40,
    dependencies: ["PD-39"],
  },
  {
    code: "PD-41",
    phase: "9. Release",
    stage: "Before submission",
    title: "Verify version, package ID, signing, URLs, pricing and countries",
    doneWhen: "Release settings verified",
    ownerRole: "PM_DEVELOPER",
    defaultOrder: 41,
    dependencies: ["PD-40"],
  },
  {
    code: "PD-42",
    phase: "9. Release",
    stage: "Submission",
    title: "Submit to store / distribution portal",
    doneWhen: "Submission confirmed",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 42,
    dependencies: ["PD-41"],
  },
  {
    code: "PD-43",
    phase: "10. Launch",
    stage: "When approved",
    title: "Confirm live listing, install/download and first-run analytics",
    doneWhen: "Live product verified",
    ownerRole: "PM_MARKETING",
    defaultOrder: 43,
    dependencies: ["PD-42"],
  },
  {
    code: "PD-44",
    phase: "10. Launch",
    stage: "Launch day",
    title:
      "Confirm analytics, crash reporting and monetisation are receiving data",
    doneWhen: "Production telemetry verified",
    ownerRole: "DEVELOPER_PM",
    defaultOrder: 44,
    dependencies: ["PD-43"],
  },
  {
    code: "PD-45",
    phase: "10. Launch",
    stage: "D+1 to D+7",
    title:
      "Monitor crashes, reviews, registration/subscription funnel and key KPIs",
    doneWhen: "Launch monitoring completed",
    ownerRole: "PM_DEVELOPER",
    defaultOrder: 45,
    dependencies: ["PD-44"],
    allowParallelWork: true,
  },
  {
    code: "PD-46",
    phase: "10. Launch",
    stage: "D+7",
    title: "Run first post-launch review and create V1.1 improvement backlog",
    doneWhen: "Post-launch actions approved",
    ownerRole: "PROJECT_MANAGEMENT",
    defaultOrder: 46,
    dependencies: ["PD-45"],
  },
];

export async function seedDevelopmentChecklist(prisma: PrismaClient) {
  for (const item of checklistItems) {
    const data = {
      phase: item.phase,
      stage: item.stage,
      title: item.title,
      description: item.title,
      doneWhen: item.doneWhen,
      mandatory: item.mandatory ?? true,
      ownerRole: item.ownerRole,
      defaultOrder: item.defaultOrder,
      requiresReview: item.requiresReview ?? true,
      allowParallelWork: item.allowParallelWork ?? false,
      dependencies: item.dependencies || [],
      applicableTypes: item.applicableTypes || ALL_PRODUCT_TYPES,
      templateVersion: TEMPLATE_VERSION,
      isActive: true,
    };

    await prisma.checklistTemplateItem.upsert({
      where: { code: item.code },
      update: data,
      create: {
        code: item.code,
        ...data,
      },
    });
  }

  return {
    version: TEMPLATE_VERSION,
    seededCount: checklistItems.length,
    missingSourceRows:
      "None. PD-01 through PD-46 are seeded from the provided FutureX checklist screenshot.",
  };
}
