'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, ArrowLeft, CalendarDays, Check, ListChecks, Megaphone, Radio, ShieldCheck } from 'lucide-react';
import { UserRole } from '@futurex/shared';
import { AppShell } from '@/components/layout/AppShell';
import { Button } from '@/components/ui/Button';
import { Progress } from '@/components/ui/Progress';
import { StatusPill } from '@/components/ui/StatusPill';
import { api } from '@/lib/api-client';
import { asArray, asRecord } from '@/lib/api-data';
import { cn, formatDate } from '@/lib/utils';
import { useAuth } from '@/features/auth/AuthContext';

type Tab = 'overview' | 'checklist' | 'channels' | 'content' | 'buzz' | 'signoff';

export function MarketingWorkspacePage() {
  const projectId = String(useParams()?.id || '');
  const { user } = useAuth();
  const manager = user?.globalRole === UserRole.ADMIN || user?.globalRole === UserRole.OWNER;
  const client = useQueryClient();
  const [tab, setTab] = useState<Tab>('overview');
  const [error, setError] = useState('');
  const [newLaunchDate, setNewLaunchDate] = useState('');
  const [reschedulePreview, setReschedulePreview] = useState<any[] | null>(null);
  const { data: projectData } = useQuery({ queryKey: ['project', projectId], queryFn: () => api.get(`/projects/${projectId}`), enabled: !!projectId });
  const project = asRecord(projectData);
  const { data: summaryData, isLoading } = useQuery({ queryKey: ['marketing', projectId, 'summary'], queryFn: () => api.get(`/projects/${projectId}/marketing/summary`), enabled: !!projectId });
  const summary = asRecord(summaryData);
  const endpoint = tab === 'overview' ? null : tab === 'signoff' ? 'signoff' : tab;
  const { data: rowsData } = useQuery({ queryKey: ['marketing', projectId, endpoint], queryFn: () => api.get(`/projects/${projectId}/marketing/${endpoint}`), enabled: !!endpoint && summary.initialized === true });
  const rows = asArray<any>(rowsData);
  const refresh = () => { client.invalidateQueries({ queryKey: ['marketing', projectId] }); client.invalidateQueries({ queryKey: ['project', projectId] }); };
  const initialize = useMutation({ mutationFn: () => api.post(`/projects/${projectId}/marketing/initialize`, {}), onSuccess: () => { setError(''); refresh(); }, onError: (e: any) => setError(e.message || 'Marketing workspace could not be initialized.') });
  const update = useMutation({ mutationFn: ({ path, body }: { path: string; body: any }) => api.patch(`/projects/${projectId}/marketing/${path}`, body), onSuccess: refresh, onError: (e: any) => setError(e.message || 'Marketing record could not be updated.') });
  const previewReschedule = useMutation({ mutationFn: () => api.get(`/projects/${projectId}/marketing/reschedule-preview?targetDate=${encodeURIComponent(newLaunchDate)}`), onSuccess: (result: any) => { setError(''); setReschedulePreview(asArray(result)); }, onError: (e: any) => setError(e.message || 'Date changes could not be previewed.') });

  if (isLoading) return <AppShell><p className="py-8 text-sm text-[#60666F]">Loading Marketing workspace...</p></AppShell>;
  if (!summary.initialized) return <AppShell><div className="mx-auto max-w-2xl space-y-5 py-8"><Link href={`/projects/${projectId}`} className="flex items-center gap-1 text-xs text-[#60666F]"><ArrowLeft className="h-3.5 w-3.5" /> Product</Link><div className="border-b border-[#E8EBEF] pb-5"><h1 className="text-xl font-semibold">Marketing & Launch</h1><p className="mt-1 text-sm text-[#60666F]">Marketing has not been initialized for {project.name || 'this Product'}.</p></div>{manager ? <Button onClick={() => initialize.mutate()} loading={initialize.isPending} leftIcon={<Megaphone className="h-4 w-4" />}>Initialize Marketing Workspace</Button> : <p className="text-sm text-[#60666F]">An Admin must initialize this workspace.</p>}{error && <p className="text-sm text-red-700">{error}</p>}</div></AppShell>;

  const tabs: { id: Tab; label: string; icon: any }[] = [{ id: 'overview', label: 'Overview', icon: Megaphone }, { id: 'checklist', label: 'Infrastructure', icon: ListChecks }, { id: 'channels', label: 'Channels', icon: Radio }, { id: 'content', label: 'Content Bank', icon: Check }, { id: 'buzz', label: 'Buzz Calendar', icon: CalendarDays }, { id: 'signoff', label: 'Launch Sign-off', icon: ShieldCheck }];
  return <AppShell fullWidth={tab === 'checklist' || tab === 'channels' || tab === 'content'}><div className="space-y-6">
    <header className="border-b border-[#E8EBEF] pb-4"><Link href={`/projects/${projectId}`} className="flex items-center gap-1 text-xs text-[#60666F] hover:text-[#2463EB]"><ArrowLeft className="h-3.5 w-3.5" /> {project.name || 'Product'}</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-semibold text-[#17191C]">Marketing & Launch</h1><p className="mt-1 text-[13px] text-[#60666F]">Infrastructure, channels, content and launch readiness.</p></div><span className={cn('text-xs font-semibold', summary.marketingReadiness === 'READY' ? 'text-[#237A57]' : 'text-[#9A6515]')}>{summary.marketingReadiness?.replace(/_/g, ' ')}</span></div></header>
    {summary.sourceConfirmationRequired > 0 && <div className="flex gap-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><AlertCircle className="h-4 w-4 shrink-0" /><span>{summary.sourceConfirmationRequired} Marketing checklist rows are marked Needs Source Confirmation. They cannot make launch readiness READY until the approved workbook wording is imported.</span></div>}
    {error && <p className="text-sm text-red-700">{error}</p>}
    <nav className="flex gap-1 overflow-x-auto border-b border-[#E8EBEF] pb-2">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={cn('flex items-center gap-1.5 whitespace-nowrap rounded-md px-3 py-1.5 text-xs', tab === item.id ? 'bg-[#EEF4FF] font-medium text-[#245EC7]' : 'text-[#60666F] hover:bg-[#F8F9FB]')}><Icon className="h-3.5 w-3.5" />{item.label}</button>; })}</nav>
    {tab === 'overview' && <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]"><section className="space-y-5"><div className="grid grid-cols-2 gap-y-4 border-b border-[#E8EBEF] pb-5 sm:grid-cols-4"><Metric label="Infrastructure" value={`${summary.checklist?.progress || 0}%`} /><Metric label="Channels Ready" value={`${summary.channels?.ready || 0} / ${summary.channels?.total || 0}`} /><Metric label="Content Ready" value={`${summary.contentBank?.ready || 0} / ${summary.contentBank?.total || 0}`} /><Metric label="Buzz Stage" value={summary.buzz?.currentStage || 'Not started'} /></div><div><div className="mb-2 flex justify-between text-xs"><span>Marketing infrastructure</span><span>{summary.checklist?.completed || 0} / {summary.checklist?.totalApplicable || 0}</span></div><Progress value={summary.checklist?.progress || 0} size="sm" /></div><div className="grid gap-2 text-xs sm:grid-cols-3"><p>{summary.checklist?.unassigned || 0} unassigned items</p><p>{summary.checklist?.blocked || 0} blocked items</p><p>{summary.contentBank?.blocked || 0} blocked assets</p></div></section><aside className="space-y-3"><h2 className="text-xs font-semibold uppercase text-[#8B929B]">Marketing Gates</h2>{(summary.gates || []).map((gate: any) => <div key={gate.code} className="flex items-center justify-between gap-3 border-b border-[#E8EBEF] py-2 text-xs"><span>{gate.name}</span>{manager && gate.status === 'READY_FOR_REVIEW' ? <button className="font-medium text-[#245EC7]" onClick={() => update.mutate({ path: `gates/${gate.id}`, body: { status: 'APPROVED' } })}>Approve</button> : <span className="text-right">{gate.status.replace(/_/g, ' ')}</span>}</div>)}</aside></div>}
    {tab === 'checklist' && <OperationalTable headers={['ID', 'Task', 'Phase', 'Responsibility', 'Assignee', 'Status', 'Evidence']} rows={rows.map((row) => [row.checklistCode, row.title, row.checklistPhase, String(row.checklistOwnerRole || '').replace(/_/g, ' '), row.assignee ? `${row.assignee.firstName} ${row.assignee.lastName}` : 'Unassigned', marketingStatusLabel(row.status), row.checklistEvidenceUrl ? <a key="evidence" href={row.checklistEvidenceUrl} target="_blank" rel="noreferrer" className="text-[#245EC7]">Open</a> : row.checklistNotes || '-'])} />}
    {tab === 'channels' && <OperationalTable headers={['Platform', 'Requirement', 'Handle / URL', '2FA', 'Status']} rows={rows.map((row) => [row.platform, row.requirement.replace(/_/g, ' '), row.publicUrl || row.handle || 'Not configured', row.twoFactorEnabled ? 'Enabled' : 'Not enabled', manager ? <SelectStatus key="status" value={row.status} values={['NOT_CREATED','IN_PROGRESS','READY','BLOCKED','N_A']} onChange={(status) => update.mutate({ path: `channels/${row.id}`, body: { status } })} /> : row.status.replace(/_/g, ' ')])} />}
    {tab === 'content' && <OperationalTable headers={['ID', 'Type', 'Stage', 'Owner', 'Asset', 'Post']} rows={rows.map((row) => [row.code, row.contentType, row.stage, row.owner ? `${row.owner.firstName} ${row.owner.lastName}` : 'Unassigned', <SelectStatus key="asset" value={row.assetStatus} values={['NOT_STARTED','IN_PRODUCTION','READY','BLOCKED']} onChange={(assetStatus) => update.mutate({ path: `content/${row.id}`, body: { assetStatus } })} />, row.postStatus.replace(/_/g, ' ')])} />}
    {tab === 'buzz' && <div>{manager && <div className="mb-4 space-y-3 border-b border-[#E8EBEF] pb-4"><div className="flex flex-wrap items-end gap-2"><label className="grid gap-1 text-xs text-[#60666F]">New launch date<input type="date" value={newLaunchDate} onChange={(event) => { setNewLaunchDate(event.target.value); setReschedulePreview(null); }} className="h-9 rounded-md border border-[#D9DEE5] px-2 text-[#17191C]" /></label><Button size="sm" variant="secondary" disabled={!newLaunchDate} loading={previewReschedule.isPending} onClick={() => previewReschedule.mutate()}>Preview Changes</Button>{reschedulePreview && <Button size="sm" disabled={update.isPending} onClick={() => update.mutate({ path: 'reschedule', body: { targetDate: newLaunchDate } }, { onSuccess: () => { setReschedulePreview(null); setNewLaunchDate(''); } })}>Confirm Reschedule</Button>}<p className="text-xs text-[#8B929B]">Completed windows keep their dates; only unfinished windows move.</p></div>{reschedulePreview && <p className="text-xs text-[#60666F]">{reschedulePreview.length} unfinished window{reschedulePreview.length === 1 ? '' : 's'} will move. New range: {reschedulePreview.length ? `${formatDate(reschedulePreview[0].startDate)} - ${formatDate(reschedulePreview[reschedulePreview.length - 1].endDate)}` : 'no date changes'}.</p>}</div>}<div className="divide-y divide-[#E8EBEF]">{rows.map((row) => <div key={row.id} className="grid gap-2 py-4 text-xs sm:grid-cols-[110px_1fr_160px_130px]"><strong>{row.stage}</strong><span className="text-[#60666F]">{row.objective}</span><span>{formatDate(row.startDate)} - {formatDate(row.endDate)}</span><SelectStatus value={row.status} values={['NOT_STARTED','IN_PROGRESS','DONE','BLOCKED']} onChange={(status) => update.mutate({ path: `buzz/${row.id}`, body: { status } })} /></div>)}</div></div>}
    {tab === 'signoff' && <OperationalTable headers={['Check', 'Requirement', 'Marketing', 'PM', 'Final']} rows={rows.map((row) => [row.checkName, row.requirement, manager ? <SelectStatus key="marketing" value={row.marketingCheck} values={['PENDING','VERIFIED','FIX_REQUIRED','N_A']} onChange={(marketingCheck) => update.mutate({ path: `signoff/${row.id}`, body: { marketingCheck } })} /> : row.marketingCheck.replace(/_/g, ' '), manager ? <SelectStatus key="pm" value={row.pmCheck} values={['PENDING','VERIFIED','FIX_REQUIRED','N_A']} onChange={(pmCheck) => update.mutate({ path: `signoff/${row.id}`, body: { pmCheck } })} /> : row.pmCheck.replace(/_/g, ' '), row.finalStatus.replace(/_/g, ' ')])} />}
  </div></AppShell>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="px-3 first:pl-0"><p className="text-[11px] text-[#8B929B]">{label}</p><p className="mt-1 text-lg font-semibold text-[#17191C]">{value}</p></div>; }
function marketingStatusLabel(status?: string) { return ({ UNASSIGNED: 'Unassigned', READY: 'Not Started', IN_PROGRESS: 'In Progress', IN_REVIEW: 'Ready for Review', BLOCKED: 'Blocked', DONE: 'Done', N_A: 'N/A' } as Record<string, string>)[status || ''] || String(status || '').replace(/_/g, ' '); }
function SelectStatus({ value, values, onChange }: { value: string; values: string[]; onChange: (value: string) => void }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="h-8 rounded-md border border-[#E8EBEF] bg-white px-2 text-xs">{values.map((item) => <option key={item} value={item}>{item.replace(/_/g, ' ')}</option>)}</select>; }
function OperationalTable({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className="overflow-x-auto rounded-lg border border-[#E8EBEF]"><table className="w-full text-left text-xs"><thead><tr className="bg-[#FAFBFC] text-[#60666F]">{headers.map((header) => <th key={header} className="px-3 py-2.5 font-medium">{header}</th>)}</tr></thead><tbody className="divide-y divide-[#E8EBEF]">{rows.map((cells, index) => <tr key={index} className="hover:bg-[#F8F9FB]">{cells.map((cell, cellIndex) => <td key={cellIndex} className="max-w-80 px-3 py-2.5 text-[#17191C]">{cell}</td>)}</tr>)}</tbody></table></div>; }
