export const MARKETING_TEMPLATE_VERSION = '2';

const rows = [
  ['Identity', 'Immediately after Product approval', 'Confirm final Product name, spelling, logo/icon and target market', 'MARKETING_ASSISTANT'],
  ['Identity', 'Immediately after Product approval', 'Define the standard username/handle to use across channels', 'MARKETING_ASSISTANT'],
  ['Identity', 'Immediately after Product approval', 'Prepare short bio, Product description and official contact details', 'MARKETING_ASSISTANT'],
  ['Ownership', 'Immediately after identity is frozen', 'Create the primary company-controlled Google account for the Product', 'MARKETING_ASSISTANT'],
  ['Ownership', 'Same day as Google account', 'Enable security/2FA and record recovery and Admin ownership', 'MARKETING_ASSISTANT'],
  ['Domain & Web', 'Early development', 'Purchase or claim the Product domain', 'MARKETING_ASSISTANT'],
  ['Domain & Web', 'After domain purchase', 'Create a basic official landing page or Product website', 'WEB_MARKETING'],
  ['Domain & Web', 'After website is accessible', 'Create and verify the Google Search Console property', 'MARKETING_ASSISTANT'],
  ['Domain & Web', 'After website is accessible', 'Set up analytics and tracking for the website', 'MARKETING_ASSISTANT'],
  ['Domain & Web', 'When sitemap is available', 'Submit the sitemap in Search Console', 'MARKETING_ASSISTANT'],
  ['Social Channels', 'As soon as Product name is frozen', 'Create or secure the YouTube channel', 'MARKETING_ASSISTANT'],
  ['Social Channels', 'As soon as Product name is frozen', 'Create or secure the Facebook Page', 'MARKETING_ASSISTANT'],
  ['Social Channels', 'As soon as Product name is frozen', 'Create or secure the TikTok account', 'MARKETING_ASSISTANT'],
  ['Social Channels', 'As soon as Product name is frozen', 'Create or secure the Instagram account', 'MARKETING_ASSISTANT'],
  ['Social Channels', 'If relevant or requested', 'Secure optional channels: Threads, X, Discord, WhatsApp Channel and Reddit', 'MARKETING_ASSISTANT'],
  ['Profile Setup', 'Immediately after channel creation', 'Upload logo/profile image and cover/banner where supported', 'MARKETING_ASSISTANT'],
  ['Profile Setup', 'Immediately after channel creation', 'Add official bio, website, contact and correct category', 'MARKETING_ASSISTANT'],
  ['Profile Setup', 'Immediately after channel creation', 'Use a consistent Product name and handle across profiles', 'MARKETING_ASSISTANT'],
  ['Profile Setup', 'Immediately after channel creation', 'Connect Facebook and Instagram in the Meta business structure', 'MARKETING_ASSISTANT'],
  ['Profile Setup', 'Before publishing', 'Add a company/Admin backup account to all critical platforms', 'MARKETING_ASSISTANT'],
  ['Digital Web', 'After social profiles are complete', 'Add official social profile links to the Product website', 'MARKETING_ASSISTANT'],
  ['Digital Web', 'When store listing exists', 'Add Play Store/App Store links to the website and social profiles', 'MARKETING_ASSISTANT'],
  ['Digital Web', 'Before buzz begins', 'Test every public link from mobile and desktop', 'MARKETING_ASSISTANT'],
  ['Content Bank', 'T-21 to T-14', 'Prepare the initial 5-10 launch creatives or videos', 'MARKETING_TEAM'],
  ['Content Bank', 'T-21 to T-14', 'Prepare teaser and curiosity content', 'MARKETING_TEAM'],
  ['Content Bank', 'T-14 to T-7', 'Prepare Product, gameplay or feature reveal content', 'MARKETING_TEAM'],
  ['Content Bank', 'T-7 to T-1', 'Prepare countdown, launch-date and launch CTA content', 'MARKETING_TEAM'],
  ['Content Bank', 'Before buzz begins', 'Prepare the posting schedule for Facebook, TikTok and YouTube', 'MARKETING_ASSISTANT'],
  ['Seed Channels', 'T-14 or earlier', 'Publish the first introduction or teaser post on each primary channel', 'MARKETING_ASSISTANT'],
  ['Seed Channels', 'T-14 to T-7', 'Publish the initial teaser and curiosity wave', 'MARKETING_ASSISTANT'],
  ['Seed Channels', 'T-7 to T-1', 'Publish the reveal, gameplay and countdown wave', 'MARKETING_ASSISTANT'],
  ['Launch', 'Launch Day', 'Publish the launch/download post across primary channels', 'MARKETING_ASSISTANT'],
  ['Launch', 'Launch Day to D+7', 'Publish gameplay highlights, reactions, reviews and milestones', 'MARKETING_ASSISTANT'],
  ['Launch', 'D+1 onward', 'Identify the strongest organic creative for paid promotion', 'MARKETING_LEAD'],
  ['Verification', 'Before initial buzz', 'Verify the Infrastructure Ready gate', 'PROJECT_MANAGER'],
  ['Verification', 'Before initial buzz', 'Verify the Channels Ready gate', 'PROJECT_MANAGER'],
  ['Verification', 'Before initial buzz', 'Verify the Content Bank Ready gate', 'PROJECT_MANAGER'],
  ['Verification', 'Before launch', 'Verify the Initial Buzz Ready gate and complete sign-off', 'PROJECT_MANAGER'],
] as const;

export const marketingChecklistItems = rows.map(([phase, stage, title, ownerRole], index) => ({
  code: `MI-${String(index + 1).padStart(2, '0')}`,
  phase,
  stage,
  title,
  description: `Timing: ${stage}. Update the checklist status and attach a public evidence link or note when applicable.`,
  doneWhen: `${title}; evidence or an operational note is recorded where applicable.`,
  ownerRole,
  mandatory: index !== 14,
  defaultOrder: index + 1,
  sourceConfirmed: true,
}));
